# Copyright 2022 Red Hat, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: v1
kind: Template
metadata:
  name: exporter-${DB_NAME}
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: exporter
  spec:
    envName: ${ENV_NAME}
    dependencies:
      - ccx-notification-writer
      - ccx-insights-results
    testing:
      iqePlugin: ccx
    jobs:
    - name: ${DB_NAME}-instance
      parallelism: 1
      completions: 1
      activeDeadlineSeconds: ${{ACTIVE_DEADLINE_SECONDS}}
      backoffLimit: 1 # Clowder doesn't support this setting as a parameter - https://coreos.slack.com/archives/CCRND57FW/p1657620480174029?thread_ts=1657619229.653889&cid=CCRND57FW
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        command:
          - ./insights-results-aggregator-exporter
        args:
          - "-output=${OUTPUT}"
          - "-metadata=true"
          - "-ignore-tables=${TABLES_TO_IGNORE}"
          - "-limit=${SELECT_LIMIT}"
        restartPolicy: Never
        resources:
          requests:
            cpu: ${CPU_REQUEST}
            memory: ${MEMORY_REQUEST}
          limits:
            cpu: ${CPU_LIMIT}
            memory: ${MEMORY_LIMIT}
        volumeMounts:
        - mountPath: /db-exporter-organization-ids
          name: db-exporter-organization-ids
          readOnly: true
        volumes:
        - name: db-exporter-organization-ids
          secret:
            secretName: db-exporter-organization-ids
            optional: true
        env:
        - name: ENV_NAME
          value: ${ENV_NAME}
        - name: INSIGHTS_RESULTS_AGGREGATOR_EXPORTER__STORAGE__DB_DRIVER
          value: postgres
        - name: INSIGHTS_RESULTS_AGGREGATOR_EXPORTER__STORAGE__PG_PARAMS
          value: ${PG_PARAMS}
        - name: INSIGHTS_RESULTS_AGGREGATOR_EXPORTER__S3__TYPE
          value: ${S3__TYPE}
        - name: INSIGHTS_RESULTS_AGGREGATOR_EXPORTER__S3__ENDPOINT_URL
          valueFrom:
            secretKeyRef:
              name: ccx-results-exporter-s3
              key: endpoint
              optional: true
        - name: INSIGHTS_RESULTS_AGGREGATOR_EXPORTER__S3__ENDPOINT_PORT
          value: ${S3__ENDPOINT_PORT}
        - name: INSIGHTS_RESULTS_AGGREGATOR_EXPORTER__S3__ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: ccx-exporter-s3-read-write
              key: aws_access_key_id
              optional: true
        - name: INSIGHTS_RESULTS_AGGREGATOR_EXPORTER__S3__SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: ccx-exporter-s3-read-write
              key: aws_secret_access_key
              optional: true
        - name: INSIGHTS_RESULTS_AGGREGATOR_EXPORTER__S3__USE_SSL
          value: "true"
        - name: INSIGHTS_RESULTS_AGGREGATOR_EXPORTER__S3__BUCKET
          valueFrom:
            secretKeyRef:
              name: ccx-results-exporter-s3
              key: bucket
              optional: true
        - name: INSIGHTS_RESULTS_AGGREGATOR_EXPORTER__S3__PREFIX
          value: ${DB_NAME}
        - name: INSIGHTS_RESULTS_AGGREGATOR_EXPORTER__LOGGING__DEBUG
          value: "${DEBUG}"
        - name: INSIGHTS_RESULTS_AGGREGATOR_EXPORTER__LOGGING__LOG_DEVEL
          value: debug
        - name: INSIGHTS_RESULTS_AGGREGATOR_EXPORTER__SENTRY__DSN
          valueFrom:
            secretKeyRef:
              key: dsn
              name: insights-aggregator-exporter-dsn
              optional: true
        - name: INSIGHTS_RESULTS_AGGREGATOR__LOGGING__LOGGING_TO_SENTRY_ENABLED
          value: ${SENTRY_ENABLED}
        - name: INSIGHTS_RESULTS_AGGREGATOR_EXPORTER__SENTRY__ENVIRONMENT
          value: ${ENV_NAME}
        - name: INSIGHTS_RESULTS_AGGREGATOR_EXPORTER__STORAGE__ORGANIZATION_IDS_CSV_FILE
          value: "${ORGANIZATION_IDS_CSV_FILE}"
        - name: INSIGHTS_RESULTS_AGGREGATOR_EXPORTER__STORAGE__ENABLE_ORG_ID_FILTERING
          value: "${ENABLE_ORG_ID_FILTERING}"
    database:
      sharedDbAppName: ${DB_NAME}

parameters:
- name: CLOWDER_ENABLED
  description: Determines if this is a Clowder deployment
  value: "true"
- name: PG_PARAMS
  value: sslmode=require
- description: Env Name
  name: ENV_NAME
  required: true
- name: ACTIVE_DEADLINE_SECONDS
  description: The maximum duration the job can run.
  value: "300" # 5 minutes
- name: BACKOFF_LIMIT
  description: The number of retries for a job.
  value: "1"
- name: IMAGE
  description: Image ID of the job.
  value: quay.io/redhat-services-prod/obsint-processing-tenant/aggregator-exporter/aggregator-exporter
- name: IMAGE_TAG
  description: The image tag.
  value: latest
- name: CPU_REQUEST
  description: Minimum amount of CPU that the job may consume.
  value: 200m
- name: MEMORY_REQUEST
  description: Minimum amount of memory that the job may consume.
  value: 5Gi
- name: CPU_LIMIT
  description: Maximum amount of CPU that the job will consume.
  value: 400m
- name: MEMORY_LIMIT
  description: Maximum amount of memory that the job will consume.
  value: 8Gi
- name: OUTPUT
  description: The exporter output (S3 or file)
  value: file
- name: TABLES_TO_IGNORE
  description: The tables to ignore
  value: ""
# Exporter configuration
- name: DEBUG
  value: "true"
- name: DB_NAME  # this has to match the annotations.clowder/database in app-interface repo (https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/45935)
  required: true
- name: S3__TYPE
  value: s3
- name: S3__ENDPOINT_PORT
  description: S3 endpoint port. Leave it empty in case you are using AWS.
- name: ORGANIZATION_IDS_CSV_FILE
  value: "/db-exporter-organization-ids/db-exporter-organization-ids.csv"
- name: ENABLE_ORG_ID_FILTERING
  value: "false"
- name: TEST_DATE
  description: A variable to force the job to run.
  value: 24/08/2023
- name: SELECT_LIMIT
  description: Number of rows to export
  value: "-1"
- name: SENTRY_ENABLED
  value: "false"