name: Go linters

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  golint:
    runs-on: ubuntu-latest
    name: Linters
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"
      - name: Build project
        run: go build
      - name: GO formatting
        run: make fmt
      - name: GO lint 
        run: make lint
      - name: GO vet
        run: make vet
      - name: gocyclo
        run: make cyclo
      - name: shellcheck
        run: make shellcheck
      - name: goconst checker
        run: make goconst
      - name: gosec checker
        run: make gosec
      - name: ineffassign checker
        run: make ineffassign
      - name: ABC metrics checker
        run: make abcgo
